# .streamlit/secrets.toml

[gcp_service_account]
type = "service_account"
project_id = "kandor-hosting"
private_key_id = "61cc4a4d9a4b051543e0d2abfedd7cc3945b6d84"
# Use triple quotes for the multi-line private key
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCpt0aJWCyfsRYr
PMrRK8kiXpf264t9ha1i2C/ISE97jPDqyIzDuAVsp+oBxY8P/7AhzFkG8otVblMl
DRQaoRdDoHIJJl4QE6iexE1ZeazIPfTZjUIxXoP4SPK2/W21pmWnDlOauap4cYbE
sRwszCtn6rhEocqEB0IHeawyNWMswq4V0I6KE4/eF7GMjCKJZ8QL82OfhZeGiXBO
KMU3qwIujWe/sISpxCJdXJMFWAtppYXXPoAMkqntqzR336mEHgjiIjPtKAK1Usfj
8TZMTjmpPT3wYgFQf0FHqCFFkExl/Fp8p6yunFKtdzZI+IOqBENAVvc/c1kX6Qcf
H9pWLDc3AgMBAAECggEAOmVbmeqDADeYnyv9xVdBj9fohgeqKXiTnk0ws8Ndxe9K
/h4fgUCSbT6hoBZwEVszKY38nA1cr/qUFU2Yu0jujlBorIlNGE8LWAXHb6AUOZpH
44tdWUtiMU44ZYpx82zb0U12quhzpZm6e3dNcISX8tuqp8Lbwe4VZCkTfPstsrqC
Zg26Wzt9xTpY1bkhvo3zDUDeyhsfva11mZXDa5entL+l3MI0+n1J0jNmzXm0Aazf
SnPGD14W8iQdkaWNoRoV/Z8Cgfg8Im7gL59P801ffm5Lr8KiDwe1+qP2nZybRrKl
2LBo7zAe50IxA3CxOu9MSCpTs931b2Qly0mprYr74QKBgQDRpdtzDju0KHCGh+Mw
YkQXigWhox+P0XxYtBXWC7YReTJa6n4w4xMkKdGIV2vYiVvxQ0crRYCxB1Lqcb/v
RT3C9HbWRACHCHUgkmYakcYLqbreP2BaNeaohM8F1qN0qy+lMGSe2AmUvlAThMN0
KSV3CBzJXmvllU1riaSRMW6ijwKBgQDPPUFqH5JHRzbMvu7Wl6tXX1mJ0zw1hFuX
iIHnxvPKTzxHHLeEsp32a1aggBkXtIZUCPnkGhnevasB0wwkKE94Z7h86iC3PvBg
1hQpQP/Nxq5IvGaaB5JjA6BaVMzoxDNObbnxNiwi9MtElBk3bFbB9ojUyDGN7HDo
oPQt7drU2QKBgGS1YdfBTJjcnEFj4ZUKf183ZEEjVTQHE86go6Sw94MpTzExV/Ew
A6/pjsgKBrp8MXiSMwvsVUe1FvWcMvFDt8mBGd0PyZkUTP+alAXLZPGRVT0SAL0V
C3qEYdaSJu8SlM6rkopjiSa0zU6zBhk08tRdR0bMXtRohkpUUoOU1WqtAoGAFP8v
0YDBYVdlxfjSWguj4IZYnA4623E9lmzOPJ17tdOxV8MhFODEAGN/s2NHJ4+yzHDc
YLAETv0IhnbLlB5BbwGTP5S5G9fUovsNr+BWCpNGtTfhbVm3CzEi3gQZfrviNuAH
JtlGP4Rt09TteSAQ6jYARw7Bdo+uIOOt2blvooECgYB9rrJASVLr4StGcM/nfwze
GOg7lLNVaBFQQcZFVocdhjj6urDXve5aNXkSqo6SC9QvpAMIoPoBcRSRMWuIB3VA
RJXMvuZ250ptiWIzs2yFSPpd2GVoKGiVdfrMMU9qJ6si5vG54rD87WApTOrFzQ1G
FiS4tBfr7E0gA6Jxwy4y+A==
-----END PRIVATE KEY-----"""
client_email = "drive-api-access@kandor-hosting.iam.gserviceaccount.com"
client_id = "111000812071341608536"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/drive-api-access%40kandor-hosting.iam.gserviceaccount.com"
universe_domain = "googleapis.com"